extends Control

signal upgrade_soldier_health_button_pressed
signal upgrade_soldier_damage_button_pressed
signal upgrade_soldier_speed_button_pressed
signal upgrade_player_health_resource_button_pressed

func _on_LifeUpgrade_upgrade_soldier_health_button_pressed():
	emit_signal("upgrade_soldier_health_button_pressed")


func _on_AtkUpgrade_upgrade_soldier_damage_button_pressed():
	emit_signal("upgrade_soldier_damage_button_pressed")


func _on_SpeedUpgrade_upgrade_soldier_speed_button_pressed():
	emit_signal("upgrade_soldier_speed_button_pressed")

func _on_HealthResourceUpgrade_upgrade_player_health_resource_button_pressed():
	emit_signal("upgrade_player_health_resource_button_pressed")
